### ISSUE TITLE
autoload.php file for TYPO3 v10

### ISSUE THREAD

**Issue by mkrappitz** [sabbelasichon/typo3-rector#2020]
The given autoload.php at https://github.com/sabbelasichon/typo3-rector/blob/master/docs/installation.md#non-composer-installations is working fine for TYPO3 v9, but not for v10, because the Bootstrap class got refactored in v10. How does the code need to be for v10? Maybe provide code examples for v9 and v10 in the documentation. 

FYI - Stack trace is:

```php
PHP Fatal error:  Uncaught Error: Call to undefined method TYPO3\CMS\Core\Core\Bootstrap::getInstance() in /www/htdocs/example/autoload.php:6
Stack trace:
#0 /.config/composer/vendor/ssch/typo3-rector-prefixed/bin/typo3-rector.php(92): require_once()
#1 /.config/composer/vendor/ssch/typo3-rector-prefixed/bin/typo3-rector.php(81): Typo3RectorPrefix20210302\AutoloadIncluder->loadIfExistsAndNotLoadedYet('./autoload.php')
#2 /.config/composer/vendor/ssch/typo3-rector-prefixed/bin/typo3-rector.php(28): Typo3RectorPrefix20210302\AutoloadIncluder->autoloadFromCommandLine()
#3 /.config/composer/vendor/ssch/typo3-rector-prefixed/bin/typo3-rector(5): require_once('/.config/compos...')
#4 {main}
  thrown in /www/htdocs/example/autoload.php on line 6
Fatal error: Uncaught Error: Call to undefined method TYPO3\CMS\Core\Core\Bootstrap::getInstance() in /www/htdocs/example/autoload.php:6
Stack trace:
#0 /.config/composer/vendor/ssch/typo3-rector-prefixed/bin/typo3-rector.php(92): require_once()
#1 /.config/composer/vendor/ssch/typo3-rector-prefixed/bin/typo3-rector.php(81): Typo3RectorPrefix20210302\AutoloadIncluder->loadIfExistsAndNotLoadedYet('./autoload.php')
#2 /.config/composer/vendor/ssch/typo3-rector-prefixed/bin/typo3-rector.php(28): Typo3RectorPrefix20210302\AutoloadIncluder->autoloadFromCommandLine()
#3 /.config/composer/vendor/ssch/typo3-rector-prefixed/bin/typo3-rector(5): require_once('/.config/compos...')
#4 {main}
  thrown in /www/htdocs/example/autoload.php on line 6
```

**Comment by mkrappitz** [comment]
Thanks a million. Works like a charm. Can you give me permissions to push a feature branch to this repo?

**Comment by sabbelasichon** [comment]
@mkrappitz Fork the project and create a PR. Btw. gimme and rector itself a star on github if you like it.

**Comment by mkrappitz** [comment]
Ah, OK. Done. Gave you a star!
