### ISSUE TITLE
Bug in prefixed version 0.9.17

### ISSUE THREAD

**Issue by mkrappitz** [sabbelasichon/typo3-rector#2077]
So far I used version 0.9.12 of the prefixed typo3-rector version and could execute rector with no problem like this:
```
php74 /.config/composer/vendor/bin/typo3-rector process typo3conf/ext/extension/ -c ./rector.php --dry-run --autoload-file ./autoload.php
```

After updating to 0.9.17 of the prefixed version the same call crashes:
```
PHP Fatal error:  Uncaught Error: Class 'Typo3RectorPrefix20210316\Composer\InstalledVersions' not found in /.config/composer/vendor/ssch/typo3-rector-prefixed/vendor/jean85/pretty-package-versions/src/PrettyVersions.php:17
Stack trace:
#0 /.config/composer/vendor/ssch/typo3-rector-prefixed/src/Console/Application.php(44): Typo3RectorPrefix20210316\Jean85\PrettyVersions::getVersion('ssch/typo3-rect...')
#1 /tmp/typo3_rector/ContainerZtOXG6U/getApplicationService.php(20): Ssch\TYPO3Rector\Console\Application->__construct(Object(Rector\Core\Configuration\Configuration), Object(Rector\Core\Bootstrap\NoRectorsLoadedReporter), Object(Typo3RectorPrefix20210316\Symplify\PackageBuilder\Console\Command\CommandNaming), Array)
#2 /tmp/typo3_rector/ContainerZtOXG6U/Ssch_TYPO3Rector_HttpKernel_Typo3RectorKernelE7d463aa654b1eed570e4b2c8fb91a09d2094058Container.php(1180): ContainerZtOXG6U\getApplicationService::do(Object(ContainerZtOXG6U\Ssch_TYPO3Rector_HttpKernel_Typo3RectorKernelE7d463aa654b1eed570e4b2c8fb91a09d2094058Container), true)
#3 in /.config/composer/vendor/ssch/typo3-rector-prefixed/vendor/jean85/pretty-package-versions/src/PrettyVersions.php on line 17
Fatal error: Uncaught Error: Class 'Typo3RectorPrefix20210316\Composer\InstalledVersions' not found in /.config/composer/vendor/ssch/typo3-rector-prefixed/vendor/jean85/pretty-package-versions/src/PrettyVersions.php:17
Stack trace:
#0 /.config/composer/vendor/ssch/typo3-rector-prefixed/src/Console/Application.php(44): Typo3RectorPrefix20210316\Jean85\PrettyVersions::getVersion('ssch/typo3-rect...')
#1 /tmp/typo3_rector/ContainerZtOXG6U/getApplicationService.php(20): Ssch\TYPO3Rector\Console\Application->__construct(Object(Rector\Core\Configuration\Configuration), Object(Rector\Core\Bootstrap\NoRectorsLoadedReporter), Object(Typo3RectorPrefix20210316\Symplify\PackageBuilder\Console\Command\CommandNaming), Array)
#2 /tmp/typo3_rector/ContainerZtOXG6U/Ssch_TYPO3Rector_HttpKernel_Typo3RectorKernelE7d463aa654b1eed570e4b2c8fb91a09d2094058Container.php(1180): ContainerZtOXG6U\getApplicationService::do(Object(ContainerZtOXG6U\Ssch_TYPO3Rector_HttpKernel_Typo3RectorKernelE7d463aa654b1eed570e4b2c8fb91a09d2094058Container), true)
#3 in /.config/composer/vendor/ssch/typo3-rector-prefixed/vendor/jean85/pretty-package-versions/src/PrettyVersions.php on line 17
```

**Comment by sabbelasichon** [comment]
@mkrappitz I am on it. I already fixed it but the version 0.9.19 is not published for some reason. Stay tuned.

**Comment by sabbelasichon** [comment]
In the meantime try to use dev-main with composer require ssch/typo3-rector-prefixed:dev-main. This works for me.

**Comment by sabbelasichon** [comment]
@mkrappitz Version 0.9.21 of prefixed version should work now. Fixed it.

**Comment by mkrappitz** [comment]
Works like a charm!
