### ISSUE TITLE
Rector error message due to invalid DocBlock

### ISSUE THREAD

**Issue by ayacoo** [sabbelasichon/typo3-rector#2735]
**Disclaimer**
The code in DocBlock is of course wrong. The question in this issue is whether we should secure the code in Rector even more?

**Error message**

```
   [applying] Ssch\TYPO3Rector\Rector\v9\v0\MoveRenderArgumentsToInitializeArgumentsMethodRector
   
PHP Notice:  Undefined property: PHPStan\PhpDocParser\Ast\PhpDoc\InvalidTagValueNode::$parameterName in /var/www/html/vendor/rector/rector/vendor/ssch/typo3-rector/src/NodeFactory/InitializeArgumentsClassMethodFactory.php on line 182
Notice: Undefined property: PHPStan\PhpDocParser\Ast\PhpDoc\InvalidTagValueNode::$parameterName in /var/www/html/vendor/rector/rector/vendor/ssch/typo3-rector/src/NodeFactory/InitializeArgumentsClassMethodFactory.php on line 182
PHP Fatal error:  Uncaught TypeError: ltrim() expects parameter 1 to be string, null given in /var/www/html/vendor/rector/rector/vendor/ssch/typo3-rector/src/NodeFactory/InitializeArgumentsClassMethodFactory.php:182
Stack trace:
#0 /var/www/html/vendor/rector/rector/vendor/ssch/typo3-rector/src/NodeFactory/InitializeArgumentsClassMethodFactory.php(182): ltrim(NULL, '$')
#1 /var/www/html/vendor/rector/rector/vendor/ssch/typo3-rector/src/NodeFactory/InitializeArgumentsClassMethodFactory.php(143): Ssch\TYPO3Rector\NodeFactory\InitializeArgumentsClassMethodFactory->getParamTagsByName(Object(PhpParser\Node\Stmt\ClassMethod))
#2 /var/www/html/vendor/rector/rector/vendor/ssch/typo3-rector/src/NodeFactory/InitializeArgumentsClassMethodFactory.php(109): Ssch\TYPO3Rector\NodeFactory\InitializeArgumentsClassMethodFactory->createStmts(Object(PhpParser\Node\Stmt\ClassMethod), Object(PhpParser\N
ode\Stmt\Class_))
```

**Code**

```
    /**
     * @param $link string
     *
     * @return $size int
     */
    public function render($link)
    {
         ...
    }
```

**Affected code**

https://github.com/sabbelasichon/typo3-rector/blob/main/src/NodeFactory/InitializeArgumentsClassMethodFactory.php#L175

**Possible solution**

I would check again in the code if `$paramTagValueNode->parameterName` is a string, so use `is_string()`. Would that be safe? I could then create a PR.

**Hint**

If all this is not possible or rather an edge case, then feel free to close the issue.

**Comment by sabbelasichon** [comment]
I have stumble upon this one too and was very happy that the error raised up, because it is invalid.

**Comment by ayacoo** [comment]
So it makes sense to fix it? :-D

**Comment by sabbelasichon** [comment]
Yes.

**Comment by helsner** [comment]
I would guess this is solved after the merge @ayacoo ?

**Comment by ayacoo** [comment]
@helsner Yes ;-)
