### ISSUE TITLE
TypoScript globalString fatal error

### ISSUE THREAD

**Issue by helsner** [sabbelasichon/typo3-rector#2805]
version: latest release (0.12.14)

Code that causes bug:
```
[globalString = _COOKIE|cookiePolicy=isSet]
    page.cookie = TEXT
    page.cookie.value = cookieIsSet
[global]
```

Error Message

```
PHP Fatal error:  Uncaught TypeError: trim() expects parameter 1 to be string, null given in ...blub../vendor/rector/rector/vendor/ssch/typo3-rector/src/FileProcessor/TypoScript/Conditions/GlobalStringConditionMatcher.php:23
Stack trace:
#0 ...blub../vendor/rector/rector/vendor/ssch/typo3-rector/src/FileProcessor/TypoScript/Conditions/GlobalStringConditionMatcher.php(23): trim(NULL)
#1 ...blub../vendor/rector/rector/vendor/ssch/typo3-rector/src/FileProcessor/TypoScript/Rector/OldConditionToExpressionLanguageTypoScriptRector.php(63): Ssch\TYPO3Rector\FileProcessor\TypoScript\Conditions\GlobalStringConditionMatcher->change('globalString = ...')
#2 ...blub../vendor/rector/rector/vendor/helmich/typo3-typoscript-parser/src/Parser/Traverser/AggregatingVisitor.php(42): Ssch\TYPO3Rector\FileProcessor\TypoScript\Rector\OldConditionToExpressionLanguageTypoScriptRector->enterNode(Object(RectorPrefix20220125\Helmich\TypoScriptParser\Parser\AST\ConditionalStatement))
#3 /Users/hel in ...blub../vendor/rector/rector/vendor/ssch/typo3-rector/src/FileProcessor/TypoScript/Conditions/GlobalStringConditionMatcher.php on line 23

Fatal error: Uncaught TypeError: trim() expects parameter 1 to be string, null given in ...blub../vendor/rector/rector/vendor/ssch/typo3-rector/src/FileProcessor/TypoScript/Conditions/GlobalStringConditionMatcher.php on line 23
```

**Comment by sabbelasichon** [comment]
Never used this condition. Incredible what TS is capable of, and scary at the same time. Could you provide me the correct solution for a transformation to Symfony Expression Language? Then i will come up with a fix.

**Comment by helsner** [comment]
Yeah, will check.
I just used rector for overall update, not even upgrades but it failed.
Don't even know if the condition is valid in the first place 😂

**Comment by helsner** [comment]
Mathias Brodala helped me out as i was not 100% sure, but it should look like the following:
`[request.getCookieParams()['cookiePolicy'] == 'isSet']`
