### ISSUE TITLE
Fatal error: Uncaught Error: Attempt to assign property "value" on null

### ISSUE THREAD

**Issue by ste101** [sabbelasichon/typo3-rector#3431]
# Bug Report

I'm getting an Fatal error:
```
Uncaught Error: Attempt to assign property "value" on null in /files/.mwsoftware/composer/vendor/ssch/typo3-rector/src/AttributeDecorator/ExtbaseCascadeAttributeDecorator.php:23
Stack trace:
#0 /files/.mwsoftware/composer/vendor/rector/rector/rules/Php80/NodeManipulator/AttributeGroupNamedArgumentManipulator.php(35): Ssch\TYPO3Rector\AttributeDecorator\ExtbaseCascadeAttributeDecorator->decorate(Object(PhpParser\Node\Attribute))
#1 /files/.mwsoftware/composer/vendor/rector/rector/rules/Php80/Rector/Class_/AnnotationToAttributeRector.php(141): Rector\Php80\NodeManipulator\AttributeGroupNamedArgumentManipulator->decorate(Array)
#2 /files/.mwsoftware/composer/vendor/rector/rector/src/Rector/AbstractRector.php(234): Rector\Php80\Rector\Class_\AnnotationToAttributeRector->refactor(Object(PhpParser\Node\Stmt\Property))
#3 /files/.mwsoftware/composer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Stmt\Property))
#4 /files/.mwsoftware/composer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#5 /files/.mwsoftware/composer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#6 /files/.mwsoftware/composer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#7 /files/.mwsoftware/composer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#8 /files/.mwsoftware/composer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#9 /files/.mwsoftware/composer/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42): PhpParser\NodeTraverser->traverse(Array)
#10 /files/.mwsoftware/composer/vendor/rector/rector/src/Application/FileProcessor.php(60): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#11 /files/.mwsoftware/composer/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(115): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#12 /files/.mwsoftware/composer/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(169): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#13 /files/.mwsoftware/composer/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(139): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#14 /files/.mwsoftware/composer/vendor/rector/rector/src/Console/Command/ProcessCommand.php(120): Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration), Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput))
#15 /files/.mwsoftware/composer/vendor/rector/rector/vendor/symfony/console/Command/Command.php(325): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#16 /files/.mwsoftware/composer/vendor/rector/rector/vendor/symfony/console/Application.php(944): RectorPrefix202306\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#17 /files/.mwsoftware/composer/vendor/rector/rector/vendor/symfony/console/Application.php(326): RectorPrefix202306\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#18 /files/.mwsoftware/composer/vendor/rector/rector/src/Console/ConsoleApplication.php(49): RectorPrefix202306\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#19 /files/.mwsoftware/composer/vendor/rector/rector/vendor/symfony/console/Application.php(212): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#20 /files/.mwsoftware/composer/vendor/rector/rector/bin/rector.php(132): RectorPrefix202306\Symfony\Component\Console\Application->run()
#21 /files/.mwsoftware/composer/vendor/rector/rector/bin/rector(5): require_once('...')
#22 /files/.mwsoftware/composer/vendor/bin/rector(117): include('...')
#23 {main}
  thrown in /files/.mwsoftware/composer/vendor/ssch/typo3-rector/src/AttributeDecorator/ExtbaseCascadeAttributeDecorator.php on line 23
```

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.0             |
| TYPO3 Rector version | 1.3.2             |
| PHP version | 8.1, 8.2             |

I tried to use rector on jobapplications (latest version from github)
https://extensions.typo3.org/extension/jobapplications

**Comment by sabbelasichon** [comment]
@ste101 I guess the reason is the following line: https://github.com/itx-informationssysteme/jobapplications/blob/develop/Classes/Domain/Model/Application.php#L115C6-L115C54.
The cascade seems wrong here, but i am not sure. I will create failing test case and try to fix it. Thanks.

**Comment by sabbelasichon** [comment]
@ste101 Could please check with the new version 1.3.3

**Comment by ste101** [comment]
This error is gone but I got another one:
```
Fatal error: Uncaught TypeError: Ssch\TYPO3Rector\Helper\StringUtility::inList(): Argument #1 ($list) must be of type string, null given, called in /files/.mwsoftware/composer/vendor/ssch/typo3-rector/src/Rector/v12/v0/tca/MigrateNullFlagRector.php on line 73 and defined in /files/.mwsoftware/composer/vendor/ssch/typo3-rector/src/Helper/StringUtility.php:37
Stack trace:
#0 /files/.mwsoftware/composer/vendor/ssch/typo3-rector/src/Rector/v12/v0/tca/MigrateNullFlagRector.php(73): Ssch\TYPO3Rector\Helper\StringUtility::inList(NULL, '...')
#1 /files/.mwsoftware/composer/vendor/ssch/typo3-rector/src/Rector/Tca/AbstractTcaRector.php(125): Ssch\TYPO3Rector\Rector\v12\v0\tca\MigrateNullFlagRector->refactorColumn(Object(PhpParser\Node\Scalar\String_), Object(PhpParser\Node\Expr\Array_))
#2 /files/.mwsoftware/composer/vendor/ssch/typo3-rector/src/Rector/Tca/AbstractTcaRector.php(66): Ssch\TYPO3Rector\Rector\Tca\AbstractTcaRector->refactorColumnList(Object(PhpParser\Node\Expr\Array_))
#3 /files/.mwsoftware/composer/vendor/rector/rector/src/Rector/AbstractRector.php(234): Ssch\TYPO3Rector\Rector\Tca\AbstractTcaRector->refactor(Object(PhpParser\Node\Expr\Array_))
#4 /files/.mwsoftware/composer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\Array_))
#5 /files/.mwsoftware/composer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Return_))
#6 /files/.mwsoftware/composer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#7 /files/.mwsoftware/composer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(Rector\Core\PhpParser\Node\CustomNode\FileWithoutNamespace))
#8 /files/.mwsoftware/composer/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#9 /files/.mwsoftware/composer/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42): PhpParser\NodeTraverser->traverse(Array)
#10 /files/.mwsoftware/composer/vendor/rector/rector/src/Application/FileProcessor.php(60): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#11 /files/.mwsoftware/composer/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(115): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#12 /files/.mwsoftware/composer/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(169): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#13 /files/.mwsoftware/composer/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(139): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#14 /files/.mwsoftware/composer/vendor/rector/rector/src/Console/Command/ProcessCommand.php(120): Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration), Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput))
#15 /files/.mwsoftware/composer/vendor/rector/rector/vendor/symfony/console/Command/Command.php(325): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#16 /files/.mwsoftware/composer/vendor/rector/rector/vendor/symfony/console/Application.php(944): RectorPrefix202306\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#17 /files/.mwsoftware/composer/vendor/rector/rector/vendor/symfony/console/Application.php(326): RectorPrefix202306\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#18 /files/.mwsoftware/composer/vendor/rector/rector/src/Console/ConsoleApplication.php(49): RectorPrefix202306\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#19 /files/.mwsoftware/composer/vendor/rector/rector/vendor/symfony/console/Application.php(212): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#20 /files/.mwsoftware/composer/vendor/rector/rector/bin/rector.php(132): RectorPrefix202306\Symfony\Component\Console\Application->run()
#21 /files/.mwsoftware/composer/vendor/rector/rector/bin/rector(5): require_once('...')
#22 /files/.mwsoftware/composer/vendor/bin/rector(117): include('...')
#23 {main}
  thrown in /files/.mwsoftware/composer/vendor/ssch/typo3-rector/src/Helper/StringUtility.php on line 37
```

And a warning:
```
[WARNING] We could identify a QueryBuilder::execute() statement to migrate, but
           not apply the changes.
                       In Short: [insert, update, delete] -> executeStatement,
           [select, count] + variations -> executeQuery.
                       Please refer to the official docs for more info: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-96972-DeprecateQueryBuilderexecute.html
```

**Comment by sabbelasichon** [comment]
The reason for this https://github.com/itx-informationssysteme/jobapplications/blob/develop/Configuration/TCA/tx_jobapplications_domain_model_posting.php#L163

**Comment by ste101** [comment]
Unfortunatelly it's not.
I removed this line, added an eval option, added a semicolon -> no change

**Comment by sabbelasichon** [comment]
I have created another release. Hope it fixes the issue

**Comment by ste101** [comment]
Unfortunatelly no change
