### ISSUE TITLE
HardenMethodSignatureOfLogicalAndAndLogicalOrRector throws "Uncaught TypeError"

### ISSUE THREAD

**Issue by koehnlein** [sabbelasichon/typo3-rector#4028]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.0            |
| TYPO3 Rector version | 1.7.0            |

When I include `Typo3LevelSetList::UP_TO_TYPO3_12`, rector fails with an "Uncaught TypeError". I will paste it at the end of this issue.

## Minimal PHP Code Causing Issue

In my repository, I build multiple constraints by `foreach`

```php
        $constraints = [];

        // `targetGroups` is an m:n relation, so we check for each target group uid, if it is part of `targetGroups`
        if ($formData && $formData->getTargetGroups()) {
            $targetOr = [];
            foreach ($formData->getTargetGroups() as $targetUid) {
                $targetOr[] = $query->contains('targetGroups', $targetUid);
            }
            $constraints[] = $query->logicalOr($targetOr);
        }

        // apply constraints
        if ($constraints) {
            $query->matching($query->logicalAnd($constraints));
        }
```

I think, especially the line `$constraints[] = $query->logicalOr($targetOr);` causes the error.

## Expected Behaviour

Of course, it would be the best, if rector would update the problematic line. If that's not possible, at least a warning with the current file name would be nice.

## Appendix

Here is the full error message.

```
Uncaught TypeError: Rector\NodeTypeResolver\PHPStan\Scope\NodeVisitor\GlobalVariableNodeVisitor::setIsGlobalVarAttribute(): Argument #1 ($stmt) must be of type PhpParser\Node\Stmt, PhpParser\Node\Expr\Assign given, called in /var/www/html/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/NodeVisitor/GlobalVariableNodeVisitor.php on line 40 and defined in /var/www/html/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/NodeVisitor/GlobalVariableNodeVisitor.php:55
Stack trace:
#0 /var/www/html/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/NodeVisitor/GlobalVariableNodeVisitor.php(40): Rector\NodeTypeResolver\PHPStan\Scope\NodeVisitor\GlobalVariableNodeVisitor->setIsGlobalVarAttribute(Object(PhpParser\Node\Expr\Assign), Array)
#1 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176): Rector\NodeTypeResolver\PHPStan\Scope\NodeVisitor\GlobalVariableNodeVisitor->enterNode(Object(PhpParser\Node\Stmt\If_))
#2 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#3 /var/www/html/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(140): PhpParser\NodeTraverser->traverse(Array)
#4 /var/www/html/vendor/rector/rector/src/Application/ChangedNodeScopeRefresher.php(96): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes(Array, '/var/www/html/p...', Object(PHPStan\Analyser\MutatingScope))
#5 /var/www/html/vendor/rector/rector/packages/PostRector/Collector/NodesToAddCollector.php(72): Rector\Core\Application\ChangedNodeScopeRefresher->refresh(Object(PhpParser\Node\Stmt\If_), Object(PHPStan\Analyser\MutatingScope))
#6 /var/www/html/vendor/ssch/typo3-rector/src/Rector/v12/v0/typo3/HardenMethodSignatureOfLogicalAndAndLogicalOrRector.php(230): Rector\PostRector\Collector\NodesToAddCollector->addNodeBeforeNode(Object(PhpParser\Node\Stmt\If_), Object(PhpParser\Node\Expr\MethodCall))
#7 /var/www/html/vendor/ssch/typo3-rector/src/Rector/v12/v0/typo3/HardenMethodSignatureOfLogicalAndAndLogicalOrRector.php(99): Ssch\TYPO3Rector\Rector\v12\v0\typo3\HardenMethodSignatureOfLogicalAndAndLogicalOrRector->handleArgumentIsVariable(Object(PhpParser\Node\Expr\MethodCall), Object(PhpParser\Node\Expr\Variable))
#8 /var/www/html/vendor/rector/rector/src/Rector/AbstractRector.php(234): Ssch\TYPO3Rector\Rector\v12\v0\typo3\HardenMethodSignatureOfLogicalAndAndLogicalOrRector->refactor(Object(PhpParser\Node\Expr\MethodCall))
#9 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\MethodCall))
#10 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))
#11 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#12 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#13 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\If_))
#14 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#15 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#16 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#17 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#18 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#19 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#20 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#21 /var/www/html/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42): PhpParser\NodeTraverser->traverse(Array)
#22 /var/www/html/vendor/rector/rector/src/Application/FileProcessor.php(60): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#23 /var/www/html/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(115): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#24 /var/www/html/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(169): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#25 /var/www/html/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(139): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#26 /var/www/html/vendor/rector/rector/src/Console/Command/ProcessCommand.php(120): Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration), Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput))
#27 /var/www/html/vendor/rector/rector/vendor/symfony/console/Command/Command.php(325): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/html/vendor/rector/rector/vendor/symfony/console/Application.php(944): RectorPrefix202306\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/html/vendor/rector/rector/vendor/symfony/console/Application.php(326): RectorPrefix202306\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/html/vendor/rector/rector/src/Console/ConsoleApplication.php(49): RectorPrefix202306\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/html/vendor/rector/rector/vendor/symfony/console/Application.php(212): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/html/vendor/rector/rector/bin/rector.php(132): RectorPrefix202306\Symfony\Component\Console\Application->run()
#33 /var/www/html/vendor/rector/rector/bin/rector(5): require_once('/var/www/html/v...')
#34 /var/www/html/vendor/bin/rector(119): include('/var/www/html/v...')
#35 {main}
  thrown in /var/www/html/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/NodeVisitor/GlobalVariableNodeVisitor.php on line 55
Fatal error: Uncaught TypeError: Rector\NodeTypeResolver\PHPStan\Scope\NodeVisitor\GlobalVariableNodeVisitor::setIsGlobalVarAttribute(): Argument #1 ($stmt) must be of type PhpParser\Node\Stmt, PhpParser\Node\Expr\Assign given, called in /var/www/html/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/NodeVisitor/GlobalVariableNodeVisitor.php on line 40 and defined in /var/www/html/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/NodeVisitor/GlobalVariableNodeVisitor.php:55
Stack trace:
#0 /var/www/html/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/NodeVisitor/GlobalVariableNodeVisitor.php(40): Rector\NodeTypeResolver\PHPStan\Scope\NodeVisitor\GlobalVariableNodeVisitor->setIsGlobalVarAttribute(Object(PhpParser\Node\Expr\Assign), Array)
#1 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176): Rector\NodeTypeResolver\PHPStan\Scope\NodeVisitor\GlobalVariableNodeVisitor->enterNode(Object(PhpParser\Node\Stmt\If_))
#2 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#3 /var/www/html/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(140): PhpParser\NodeTraverser->traverse(Array)
#4 /var/www/html/vendor/rector/rector/src/Application/ChangedNodeScopeRefresher.php(96): Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes(Array, '/var/www/html/p...', Object(PHPStan\Analyser\MutatingScope))
#5 /var/www/html/vendor/rector/rector/packages/PostRector/Collector/NodesToAddCollector.php(72): Rector\Core\Application\ChangedNodeScopeRefresher->refresh(Object(PhpParser\Node\Stmt\If_), Object(PHPStan\Analyser\MutatingScope))
#6 /var/www/html/vendor/ssch/typo3-rector/src/Rector/v12/v0/typo3/HardenMethodSignatureOfLogicalAndAndLogicalOrRector.php(230): Rector\PostRector\Collector\NodesToAddCollector->addNodeBeforeNode(Object(PhpParser\Node\Stmt\If_), Object(PhpParser\Node\Expr\MethodCall))
#7 /var/www/html/vendor/ssch/typo3-rector/src/Rector/v12/v0/typo3/HardenMethodSignatureOfLogicalAndAndLogicalOrRector.php(99): Ssch\TYPO3Rector\Rector\v12\v0\typo3\HardenMethodSignatureOfLogicalAndAndLogicalOrRector->handleArgumentIsVariable(Object(PhpParser\Node\Expr\MethodCall), Object(PhpParser\Node\Expr\Variable))
#8 /var/www/html/vendor/rector/rector/src/Rector/AbstractRector.php(234): Ssch\TYPO3Rector\Rector\v12\v0\typo3\HardenMethodSignatureOfLogicalAndAndLogicalOrRector->refactor(Object(PhpParser\Node\Expr\MethodCall))
#9 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\MethodCall))
#10 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))
#11 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#12 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#13 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\If_))
#14 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#15 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#16 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#17 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#18 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#19 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#20 /var/www/html/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#21 /var/www/html/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42): PhpParser\NodeTraverser->traverse(Array)
#22 /var/www/html/vendor/rector/rector/src/Application/FileProcessor.php(60): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#23 /var/www/html/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(115): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#24 /var/www/html/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(169): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#25 /var/www/html/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(139): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#26 /var/www/html/vendor/rector/rector/src/Console/Command/ProcessCommand.php(120): Rector\Core\Application\ApplicationFileProcessor->run(Object(Rector\Core\ValueObject\Configuration), Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput))
#27 /var/www/html/vendor/rector/rector/vendor/symfony/console/Command/Command.php(325): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/html/vendor/rector/rector/vendor/symfony/console/Application.php(944): RectorPrefix202306\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/html/vendor/rector/rector/vendor/symfony/console/Application.php(326): RectorPrefix202306\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/html/vendor/rector/rector/src/Console/ConsoleApplication.php(49): RectorPrefix202306\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/html/vendor/rector/rector/vendor/symfony/console/Application.php(212): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/html/vendor/rector/rector/bin/rector.php(132): RectorPrefix202306\Symfony\Component\Console\Application->run()
#33 /var/www/html/vendor/rector/rector/bin/rector(5): require_once('/var/www/html/v...')
#34 /var/www/html/vendor/bin/rector(119): include('/var/www/html/v...')
#35 {main}
  thrown in /var/www/html/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/NodeVisitor/GlobalVariableNodeVisitor.php on line 55
```

**Comment by akiessling** [comment]
I'm having the same issue, even manually fixing the logicalOr and logicalAnd does not help :/

**Comment by sabbelasichon** [comment]
The error is gone. We have removed the rule. It was to fragile and complex. We are sorry but we are striving for stability

**Comment by koehnlein** [comment]
This is not what I had hoped for. But thanks anyway for all your work.
