### ISSUE TITLE
rectorphp or rector have a problem with fluent function \TYPO3\CMS\Core\Database\Query\Expression\CompositeExpression::add

### ISSUE THREAD

**Issue by hdietrich-timespin** [sabbelasichon/typo3-rector#4196]
The following Code throw an Error durinfg process

rectorphp version 2.0.0 

```
return RectorConfig::configure()
 ->withSets([
        Typo3LevelSetList::UP_TO_TYPO3_12,
        LevelSetList::UP_TO_PHP_82,
    ])
    // uncomment to reach your current PHP version
    // ->withPhpSets()
    ->withRules([
        AddVoidReturnTypeWhereNoReturnRector::class,
    ]);
```

Code: 
```
 /** @var \TYPO3\CMS\Core\Database\Query\QueryBuilder $queryBuilder */
            $or = $queryBuilder->expr()->or();
            $or->add($queryBuilder->expr()->like('city', ":search"))
                  ->add($queryBuilder->expr()->like('zip', ":search"))
                  ->add($queryBuilder->expr()->like('company_name', ":search"))
                  ->add($queryBuilder->expr()->like('scope', ":search"))
            ;
```
Error:  (see trace in the end of that description!) 
```
[ERROR] Could not process
         "/www/typo3conf
         /ext/myext/Classes/Domain/Repository/CertificateGlkRepository.php" file, due to:
         "System error: "Scope not available on "PhpParser\Node\Expr\MethodCall" node, but is required by a
         refactorWithScope() method of "Rector\Renaming\Rector\MethodCall\RenameMethodRector" rule. Fix scope refresh on
         changed nodes first"
```

if i change the Code to: 
```
            /** @var \TYPO3\CMS\Core\Database\Query\QueryBuilder $queryBuilder */
            $or = $queryBuilder->expr()->or();
            $or->add($queryBuilder->expr()->like('city', ":search"));
            $or->add($queryBuilder->expr()->like('zip', ":search"));
            $or->add($queryBuilder->expr()->like('company_name', ":search"));
            $or->add($queryBuilder->expr()->like('scope', ":search"));
```

It will be processed without Error: 
![grafik](https://github.com/rectorphp/rector/assets/117842214/8571e7fd-3063-4f7f-8763-897743b36e5e)

Errortrace: 
```

[ERROR] Could not process
         "/www/typo3conf
         /ext/myext/Classes/Domain/Repository/CertificateGlkRepository.php" file, due to:
         "System error: "Scope not available on "PhpParser\Node\Expr\MethodCall" node, but is required by a
         refactorWithScope() method of "Rector\Renaming\Rector\MethodCall\RenameMethodRector" rule. Fix scope refresh on
         changed nodes first"

         Stack trace:
         #0 /www/typo3-rector-2.0.0/vendor/rector/rector/src/Rector/AbstractRector.php(136):
         Rector\Rector\AbstractScopeAwareRector->refactor()
         #1
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(113): Rector\Rector\AbstractRector->enterNode()
         #2
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(133): PhpParser\NodeTraverser->traverseNode()
         #3
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(133): PhpParser\NodeTraverser->traverseNode()
         #4
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(196): PhpParser\NodeTraverser->traverseNode()
         #5
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(105): PhpParser\NodeTraverser->traverseArray()
         #6
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(196): PhpParser\NodeTraverser->traverseNode()
         #7
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(105): PhpParser\NodeTraverser->traverseArray()
         #8
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(196): PhpParser\NodeTraverser->traverseNode()
         #9
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(105): PhpParser\NodeTraverser->traverseArray()
         #10
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(196): PhpParser\NodeTraverser->traverseNode()
         #11
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(105): PhpParser\NodeTraverser->traverseArray()
         #12
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(196): PhpParser\NodeTraverser->traverseNode()
         #13
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTrav
         erser.php(85): PhpParser\NodeTraverser->traverseArray()
         #14
         /www/typo3-rector-2.0.0/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverse
         r.php(41): PhpParser\NodeTraverser->traverse()
         #15 /www/typo3-rector-2.0.0/vendor/rector/rector/src/Application/FileProcessor.php(105):
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()
         #16
         /www/typo3-rector-2.0.0/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(1
         84): Rector\Application\FileProcessor->processFile()
         #17
         /www/typo3-rector-2.0.0/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(1
         61): Rector\Application\ApplicationFileProcessor->processFile()
         #18
         /www/typo3-rector-2.0.0/vendor/rector/rector/src/Console/Command/WorkerCommand.php(118):
         Rector\Application\ApplicationFileProcessor->processFiles()
         #19
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTra
         it.php(111): Rector\Console\Command\WorkerCommand->Rector\Console\Command\{closure}()
         #20
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):
         RectorPrefix202402\Evenement\EventEmitter->emit()
         #21
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTra
         it.php(111): RectorPrefix202402\Clue\React\NDJson\Decoder->handleData()
         #22 /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/react/stream/src/Util.php(62):
         RectorPrefix202402\Evenement\EventEmitter->emit()
         #23
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/evenement/evenement/src/EventEmitterTra
         it.php(111): RectorPrefix202402\React\Stream\Util::RectorPrefix202402\React\Stream\{closure}()
         #24
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.p
         hp(154): RectorPrefix202402\Evenement\EventEmitter->emit()
         #25
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.p
         hp(201): RectorPrefix202402\React\Stream\DuplexResourceStream->handleData()
         #26
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.p
         hp(173): RectorPrefix202402\React\EventLoop\StreamSelectLoop->waitForStreamActivity()
         #27 /www/typo3-rector-2.0.0/vendor/rector/rector/src/Console/Command/WorkerCommand.php(89):
         RectorPrefix202402\React\EventLoop\StreamSelectLoop->run()
         #28
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/symfony/console/Command/Command.php(327
         ): Rector\Console\Command\WorkerCommand->execute()
         #29
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/symfony/console/Application.php(960):
         RectorPrefix202402\Symfony\Component\Console\Command\Command->run()
         #30
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/symfony/console/Application.php(333):
         RectorPrefix202402\Symfony\Component\Console\Application->doRunCommand()
         #31 /www/typo3-rector-2.0.0/vendor/rector/rector/src/Console/ConsoleApplication.php(53):
         RectorPrefix202402\Symfony\Component\Console\Application->doRun()
         #32
         /www/typo3-rector-2.0.0/vendor/rector/rector/vendor/symfony/console/Application.php(216):
         Rector\Console\ConsoleApplication->doRun()
         #33 /www/typo3-rector-2.0.0/vendor/rector/rector/bin/rector.php(130):
         RectorPrefix202402\Symfony\Component\Console\Application->run()
         #34 /www/typo3-rector-2.0.0/vendor/rector/rector/bin/rector(5): require_once('...')
         #35 /www/typo3-rector-2.0.0/vendor/bin/rector(119): include('...')
         #36 {main}". On line: 25
```

**Comment by hdietrich-timespin** [comment]
is related to https://github.com/rectorphp/rector/issues/8563. I test the patch fom @samsonasik , but it do not solved the problem https://github.com/rectorphp/rector-src/pull/5743. 

Can you help?

**Comment by samsonasik** [comment]
Like mentioned on original issue, It is better to create a github repo with step by step to reproduce, otherwise, nothing we can do.

**Comment by hdietrich-timespin** [comment]
So I have reproduceable repo here with branch for this issue https://github.com/hdietrich-timespin/typo3-rector-testrepo/tree/bug_issues_4196. The Repo is a fork of https://github.com/sabbelasichon/typo3-rector.git

You can start start rector process with, and you can see the Error 

`
/typo3-rector-testrepo/MyProject$ php82 ../vendor/bin/rector  process typo3conf/ext/t3tstest/Classes/Domain/Repository --dry-run -vvv --debug
`

**Comment by samsonasik** [comment]
Fixed at https://github.com/rectorphp/rector-src/pull/5743

**Comment by hdietrich-timespin** [comment]
Yes it works fine.  Thanks!

**Comment by hdietrich-timespin** [comment]
Is it not possible that the changed code more human readable is?

**Comment by hdietrich-timespin** [comment]
If I do not use fluent calls the rector changes are very better: 

![grafik](https://github.com/sabbelasichon/typo3-rector/assets/117842214/f5721d49-df85-4b4e-a53d-7ca4033cbf49)
