### ISSUE TITLE
[BUG]: Class "Rector\Symfony\NodeAnalyzer\Command\SetAliasesMethodCallExtractor" does not exist

### ISSUE THREAD

**Issue by mbrodala** [sabbelasichon/typo3-rector#4285]
### Minimal PHP Code Causing Issue

```php
<?php

declare(strict_types=1);

/*
 * This file is part of the package t3g/file_variants.
 *
 * For the full copyright and license information, please read the
 * LICENSE file that was distributed with this source code.
 */

use Rector\Config\RectorConfig;
use Ssch\TYPO3Rector\Set\Typo3SetList;
use Ssch\TYPO3Rector\TYPO312\v3\MigrateItemsIndexedKeysToAssociativeRector;

return RectorConfig::configure()
    ->withPaths([
        // ...
    ])
    ->withSets([
        Typo3SetList::TYPO3_12,
    ])
;
```

### Applied rules

None, Rector fails to run:

```
$ rector --config=Build/rector.php --dry-run --no-progress-bar
PHP Fatal error:  Uncaught ReflectionException: Class "Rector\Symfony\NodeAnalyzer\Command\SetAliasesMethodCallExtractor" does not exist in /.../vendor/rector/rector/vendor/illuminate/container/Container.php:782
Stack trace:
#0 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(782): ReflectionClass->__construct('Rector\\Symfony\\...')
#1 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(681): RectorPrefix202407\Illuminate\Container\Container->build('Rector\\Symfony\\...')
#2 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(628): RectorPrefix202407\Illuminate\Container\Container->resolve('Rector\\Symfony\\...', Array)
#3 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(906): RectorPrefix202407\Illuminate\Container\Container->make('Rector\\Symfony\\...')
#4 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(836): RectorPrefix202407\Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(806): RectorPrefix202407\Illuminate\Container\Container->resolveDependencies(Array)
#6 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(252): RectorPrefix202407\Illuminate\Container\Container->build('Ssch\\TYPO3Recto...')
#7 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(779): RectorPrefix202407\Illuminate\Container\Container->RectorPrefix202407\Illuminate\Container\{closure}(Object(Rector\Config\RectorConfig), Array)
#8 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(681): RectorPrefix202407\Illuminate\Container\Container->build(Object(Closure))
#9 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(628): RectorPrefix202407\Illuminate\Container\Container->resolve('Ssch\\TYPO3Recto...', Array)
#10 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(471): RectorPrefix202407\Illuminate\Container\Container->make('Ssch\\TYPO3Recto...')
#11 [internal function]: RectorPrefix202407\Illuminate\Container\Container->RectorPrefix202407\Illuminate\Container\{closure}()
#12 /.../vendor/rector/rector/vendor/illuminate/container/ContextualBindingBuilder.php(72): iterator_to_array(Object(RectorPrefix202407\Illuminate\Container\RewindableGenerator))
#13 /.../vendor/rector/rector/vendor/illuminate/container/Util.php(38): RectorPrefix202407\Illuminate\Container\ContextualBindingBuilder->RectorPrefix202407\Illuminate\Container\{closure}(Object(Rector\Config\RectorConfig))
#14 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(885): RectorPrefix202407\Illuminate\Container\Util::unwrapIfClosure(Object(Closure), Object(Rector\Config\RectorConfig))
#15 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(836): RectorPrefix202407\Illuminate\Container\Container->resolvePrimitive(Object(ReflectionParameter))
#16 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(806): RectorPrefix202407\Illuminate\Container\Container->resolveDependencies(Array)
#17 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(681): RectorPrefix202407\Illuminate\Container\Container->build('Rector\\Configur...')
#18 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(628): RectorPrefix202407\Illuminate\Container\Container->resolve('Rector\\Configur...', Array)
#19 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(906): RectorPrefix202407\Illuminate\Container\Container->make('Rector\\Configur...')
#20 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(836): RectorPrefix202407\Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#21 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(806): RectorPrefix202407\Illuminate\Container\Container->resolveDependencies(Array)
#22 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(252): RectorPrefix202407\Illuminate\Container\Container->build('Rector\\Console\\...')
#23 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(779): RectorPrefix202407\Illuminate\Container\Container->RectorPrefix202407\Illuminate\Container\{closure}(Object(Rector\Config\RectorConfig), Array)
#24 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(681): RectorPrefix202407\Illuminate\Container\Container->build(Object(Closure))
#25 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(628): RectorPrefix202407\Illuminate\Container\Container->resolve('Rector\\Console\\...', Array)
#26 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(471): RectorPrefix202407\Illuminate\Container\Container->make('Rector\\Console\\...')
#27 [internal function]: RectorPrefix202407\Illuminate\Container\Container->RectorPrefix202407\Illuminate\Container\{closure}()
#28 /.../vendor/rector/rector/vendor/illuminate/container/ContextualBindingBuilder.php(72): iterator_to_array(Object(RectorPrefix202407\Illuminate\Container\RewindableGenerator))
#29 /.../vendor/rector/rector/vendor/illuminate/container/Util.php(38): RectorPrefix202407\Illuminate\Container\ContextualBindingBuilder->RectorPrefix202407\Illuminate\Container\{closure}(Object(Rector\Config\RectorConfig))
#30 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(885): RectorPrefix202407\Illuminate\Container\Util::unwrapIfClosure(Object(Closure), Object(Rector\Config\RectorConfig))
#31 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(836): RectorPrefix202407\Illuminate\Container\Container->resolvePrimitive(Object(ReflectionParameter))
#32 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(806): RectorPrefix202407\Illuminate\Container\Container->resolveDependencies(Array)
#33 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(681): RectorPrefix202407\Illuminate\Container\Container->build('Rector\\Console\\...')
#34 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(628): RectorPrefix202407\Illuminate\Container\Container->resolve('Rector\\Console\\...', Array)
#35 /.../vendor/rector/rector/src/DependencyInjection/LazyContainerFactory.php(250): RectorPrefix202407\Illuminate\Container\Container->make('Rector\\Console\\...')
#36 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(779): Rector\DependencyInjection\LazyContainerFactory::Rector\DependencyInjection\{closure}(Object(Rector\Config\RectorConfig), Array)
#37 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(681): RectorPrefix202407\Illuminate\Container\Container->build(Object(Closure))
#38 /.../vendor/rector/rector/vendor/illuminate/container/Container.php(638): RectorPrefix202407\Illuminate\Container\Container->resolve('RectorPrefix202...')
#39 /.../vendor/rector/rector/bin/rector.php(129): RectorPrefix202407\Illuminate\Container\Container->get('RectorPrefix202...')
#40 /.../vendor/rector/rector/bin/rector(5): require_once('/.../ve...')
#41 /.../vendor/bin/rector(119): include('/.../ve...')
#42 {main}
```

### Expected Behaviour

Rector should run.

### Package Version

v2.6.1

### PHP Version

8.2.0

### TYPO3 Version

12.4

### Notes

The mentioned class was removed, see https://github.com/rectorphp/rector/issues/8708

Example failing build: https://github.com/TYPO3GmbH/ext-file-variants/actions/runs/9753757743/job/26919543124

**Comment by derhansen** [comment]
Seems to be related to new rector/rector release - see https://github.com/rectorphp/rector/releases/tag/1.2.0

Downgrading to 1.1.1 works as a temporary solution.

**Comment by ErHaWeb** [comment]
Adding
```php
->withSkip([
    CommandConfigurationToAttributeRector::class,
])
```
also works as a temporary solution with rector/rector 1.2.0
